### ISSUE TITLE
F-string not supported for much older python 3

### ISSUE THREAD

**Issue by astrochun** [mikeckennedy/python-shorts#1]
Great pyshorts video!

In your python 3 pythonic solution for `dict` merging, you used `f`-strings:
https://github.com/mikeckennedy/python-shorts/blob/d778932b13c51979fb2191fe45d11799c2777916/shorts/01-merging-dictionaries/v2_pythonic_py3_merge.py#L11-L16

I have no issue with `f`-strings; this is a minor issue: You noted it as "python 3", which implies python 3.0 and above. However, `f`-strings with debug requires python 3.8 and above.

Indeed, pythonistas should stop using python 3.6 and earlier, but even then, your code will not work for python 3.7.

I know this distracts for the focus of dictionary merging and would have complicated the exercise with different print statements. Perhaps some additional comments in the code would suffice.

**Comment by mikeckennedy** [comment]
Hey thanks for the feedback. I'm glad you like in the videos.

I do know that it was Python 3.6 that added F strings. But at this point, even Python 3.6 is no longer supported. So when I was talking about this being a feature of Python 3, I really meant the active versions of Python 3 that are still used in the world.
